### ISSUE TITLE
Keypress event is deprecated

### ISSUE THREAD

**Issue by snnsnn** [fabiospampinato/shortcuts#4]
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event

**Comment by fabiospampinato** [comment]
Yeah, but it doesn't really matter since it's supported consistently and basically can't be deleted from the platform.

I don't remember exactly now, but I'm using both keydown and keypress on purpose for some reason, there was something that the keypress event gave me that keydown didn't, if I remember correctly 🤔 

I don't think it's worth changing this even if that was wrong.
